In [76]:
import numpy  as np
import pandas as pd 
import matplotlib.pyplot as plt 
import json   as j 

# 
import seaborn as sns 

import warnings
warnings.filterwarnings('ignore')

print('numpy   version , ' , np.__version__)
print('pandnas version , ' , pd.__version__)

numpy   version ,  1.24.3
pandnas version ,  1.5.3


In [3]:
def aryInfo(ary) : 
    print('type - ' , type(ary)) 
    print('shape - ' , ary.shape)
    print('ndim  - ' , ary.ndim)
    print('dtype - ' , ary.dtype)
    print()
    print('data  -')
    print(ary) 

def seriesInfo(s) :
    print('type   - ' , type(s)) 
    print('index  - ' , s.index) 
    print('values - ' , s.values)
    print('dtype  - ' , s.dtype)
    print()
    print('data  -')
    print(s) 

def frmInfo(frm) : 
    print('type    - ' , type(frm))
    print('shape   - ' , frm.shape)
    print('ndim    - ' , frm.ndim)
    print('row idx - ' , frm.index , type(frm.index))
    print('col idx - ' , frm.columns , type(frm.columns))
    print('values  - ' , type(frm.values))
    print(frm.values)
    print('data - ')
    display(frm)

- DataFrame(표 형식 - 행, 열) , .csv 파일을 읽어서  
- 행 인덱스 , 열 인덱스
- pd.DataFrame(data =  , index = , columns = )

In [17]:
print('dict 를 이용한 프레임 생성 - ')
frm = pd.DataFrame({
    'feature01' : [1,2,3] , 
    'feature02' : [1,2,3] ,
    'feature03' : [1,2,3]
})
print('type    - ' , type(frm))
print('shape   - ' , frm.shape)
print('ndim    - ' , frm.ndim)
print('row idx - ' , frm.index , type(frm.index))
print('col idx - ' , frm.columns , type(frm.columns))
print('values  - ' , type(frm.values))
print(frm.values)
print('data - ')
display(frm)

dict 를 이용한 프레임 생성 - 
type    -  <class 'pandas.core.frame.DataFrame'>
shape   -  (3, 3)
ndim    -  2
row idx -  RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
col idx -  Index(['feature01', 'feature02', 'feature03'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  -  <class 'numpy.ndarray'>
[[1 1 1]
 [2 2 2]
 [3 3 3]]
data - 


feature01  feature02  feature03
0          1          1          1
1          2          2          2
2          3          3          3

In [21]:
print('list 이용한 프레임 생성 - ') 
frm = pd.DataFrame(data  =  [['섭섭해', 'm', True],
                             ['동아대', 'm', False] ] ,
                   columns = ['이름', '성별', '결혼여부'] , 
                   index   = [ 'user_'+str(idx) for idx in range(2) ])
frm

list 이용한 프레임 생성 - 


이름 성별   결혼여부
user_0  섭섭해  m   True
user_1  동아대  m  False

In [36]:
print('pre-procssing(전처리) - 열 이름변경 , rename() ') 
print('rename(columns|index = {old_columns : new_columns} , inplace = )')
print('컬럼명을 영문으로 변경한다면 - ') 
# print('dir - ' , dir(frm))

frm.rename(columns = {'이름' : 'name' , '성별' : 'gender' , '결혼여부' : 'marriage'} , 
           inplace = True , 
           index   = {'user_0' : 'customer_0' , 'user_1' : 'customer_1'} )

print('index   - ' , frm.index)
print('columns - ' , frm.columns)
print()

# for idx in frm.columns : 
#     print(idx)

pre-procssing(전처리) - 열 이름변경 , rename() 
rename(columns|index = {old_columns : new_columns} , inplace = )
컬럼명을 영문으로 변경한다면 - 
index   -  Index(['customer_0', 'customer_1'], dtype='object')
columns -  Index(['name', 'gender', 'marriage'], dtype='object')

name
gender
marriage


In [41]:
print('데이터 추출 -') 
print('indexing - \n' , frm['name']  , type(frm['name']))

데이터 추출 -
indexing - 
 customer_0    섭섭해
customer_1    동아대
Name: name, dtype: object <class 'pandas.core.series.Series'>


In [50]:
print('데이터 추가 - ') 
frm['age'] = [10, 20]

데이터 추가 - 


In [51]:
frm

name gender  marriage  age
customer_0  섭섭해      m      True   10
customer_1  동아대      m     False   20

In [55]:
print('열 삭제 - ') 
del frm['age']
# def frm[['name' , 'marriage']] 

열 삭제 - 


KeyError: 'age'

In [54]:
frm

name gender  marriage
customer_0  섭섭해      m      True
customer_1  동아대      m     False

In [61]:
print('만약, 행 인덱싱을 하고 싶다면? -  정답 ; 무조건 슬라이싱') 
print('정수라벨, 문자라벨 모두 가능')
print('정수 인덱싱은 -1 , 문자 인덱싱은 해당 인덱스를 포함')
print(frm[ 0 : 1 ])
print(frm[   : 'customer_0' ])


만약, 행 인덱싱을 하고 싶다면? -  정답 ; 무조건 슬라이싱
정수라벨, 문자라벨 모두 가능
정수 인덱싱은 -1 , 문자 인덱싱은 해당 인덱스를 포함
           name gender  marriage
customer_0  섭섭해      m      True
           name gender  marriage
customer_0  섭섭해      m      True


In [75]:
print('type - ' , type(frm['name']))
print(frm['name'])
print()
print(frm['name']['customer_0'] , type(frm['name']['customer_0']))
print(frm['name'][ : 'customer_0'] , type(frm['name'][ : 'customer_0']))


type -  <class 'pandas.core.series.Series'>
customer_0    섭섭해
customer_1    동아대
Name: name, dtype: object

섭섭해 <class 'str'>
customer_0    섭섭해
Name: name, dtype: object <class 'pandas.core.series.Series'>


- json 데이터 프레임 생성

In [81]:
import urllib

url = 'http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=f5eef3421c602c6cb7ea224104795888&targetDt=20120101'
response = urllib.request.urlopen(url)
# print(response.read())
result = j.loads(response.read())
print('type - ' , type(result))
print('keys - ' , result.keys())

type -  <class 'dict'>
keys -  dict_keys(['boxOfficeResult'])


In [87]:
data = result['boxOfficeResult']['dailyBoxOfficeList']
print('type - ' , type(data))

type -  <class 'list'>


돌발퀴즈
- rnum , movieNm, salesAmt 
- 위 세가지 값을 추출하여 데이터 프레임을 만들어보자
- 컬럼명 변경 - 랭킹, 영화제목, 판매금액


In [91]:
print('case01 - ')
movieFrm = pd.DataFrame(data)[['rnum','movieNm','salesAmt']]
movieFrm.rename(columns = {'rnum'    : '랭킹' ,
                           'movieNm' : '영화제목' ,
                           'salesAmt': '판매금액'} ,inplace = True)
movieFrm

case01 - 


랭킹                                 영화제목        판매금액
0   1                       미션임파서블:고스트프로토콜  2776060500
1   2                                마이 웨이  1189058500
2   3                        셜록홈즈 : 그림자 게임  1176022500
3   4                               퍼펙트 게임   644532000
4   5                        프렌즈: 몬스터섬의비밀    436753500
5   6                                라이온 킹   507115500
6   7                               오싹한 연애   344871000
7   8   극장판 포켓몬스터 베스트 위시「비크티니와 백의 영웅 레시라무」   167809500
8   9                            앨빈과 슈퍼밴드3   137030000
9  10  극장판 포켓몬스터 베스트 위시 「비크티니와 흑의 영웅 제크로무」   125535500

In [98]:
print('case02 - ') 
lst = []
for row in data : 
    lst.append( [row['rnum'] , row['movieNm'] , row['salesAmt']] )
print()
print(lst)
movieFrm = pd.DataFrame(lst)
display(movieFrm)

case02 - 

[['1', '미션임파서블:고스트프로토콜', '2776060500'], ['2', '마이 웨이', '1189058500'], ['3', '셜록홈즈 : 그림자 게임', '1176022500'], ['4', '퍼펙트 게임', '644532000'], ['5', '프렌즈: 몬스터섬의비밀 ', '436753500'], ['6', '라이온 킹', '507115500'], ['7', '오싹한 연애', '344871000'], ['8', '극장판 포켓몬스터 베스트 위시「비크티니와 백의 영웅 레시라무」', '167809500'], ['9', '앨빈과 슈퍼밴드3', '137030000'], ['10', '극장판 포켓몬스터 베스트 위시 「비크티니와 흑의 영웅 제크로무」', '125535500']]


0                                    1           2
0   1                       미션임파서블:고스트프로토콜  2776060500
1   2                                마이 웨이  1189058500
2   3                        셜록홈즈 : 그림자 게임  1176022500
3   4                               퍼펙트 게임   644532000
4   5                        프렌즈: 몬스터섬의비밀    436753500
5   6                                라이온 킹   507115500
6   7                               오싹한 연애   344871000
7   8   극장판 포켓몬스터 베스트 위시「비크티니와 백의 영웅 레시라무」   167809500
8   9                            앨빈과 슈퍼밴드3   137030000
9  10  극장판 포켓몬스터 베스트 위시 「비크티니와 흑의 영웅 제크로무」   125535500

- 데이터 조작(잘 꺼내야된다!!) 
- 프레임은 기본 열 인덱스를 사용하고 , 행 인덱스를 위해서는 슬라이싱 
- loc[] 라벨값 , iloc[] 정수값 : 인덱서
    

In [10]:
# frm = pd.DataFrame( np.random.normal(50, 2, (3,4)) )
frm = pd.DataFrame( np.arange(100, 112).reshape(3,4) ,
                    index   = [ 'row_'+str(idx) for idx in range(1,4)],
                    columns = [ 'feature_'+str(idx) for idx in range(1,5)])
frmInfo(frm)

type    -  <class 'pandas.core.frame.DataFrame'>
shape   -  (3, 4)
ndim    -  2
row idx -  Index(['row_1', 'row_2', 'row_3'], dtype='object') <class 'pandas.core.indexes.base.Index'>
col idx -  Index(['feature_1', 'feature_2', 'feature_3', 'feature_4'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  -  <class 'numpy.ndarray'>
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]]
data - 


feature_1  feature_2  feature_3  feature_4
row_1        100        101        102        103
row_2        104        105        106        107
row_3        108        109        110        111

In [11]:
frm.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, row_1 to row_3
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature_1  3 non-null      int32
 1   feature_2  3 non-null      int32
 2   feature_3  3 non-null      int32
 3   feature_4  3 non-null      int32
dtypes: int32(4)
memory usage: 72.0+ bytes


In [12]:
frm.describe()

feature_1  feature_2  feature_3  feature_4
count        3.0        3.0        3.0        3.0
mean       104.0      105.0      106.0      107.0
std          4.0        4.0        4.0        4.0
min        100.0      101.0      102.0      103.0
25%        102.0      103.0      104.0      105.0
50%        104.0      105.0      106.0      107.0
75%        106.0      107.0      108.0      109.0
max        108.0      109.0      110.0      111.0

In [27]:
print('인덱스 사용 - loc[]') 
# frm[] - 열 인덱스
print('라벨값 기반 - ' , frm.loc['row_1'].values)
print('정수값 기반 - ' , frm.iloc[0].values)
print()
print('멀티인덱스 [] - \n' , frm.loc[ [ 'row_1' , 'row_3'] ] )
print('슬라이싱   [] - \n' , frm.loc[ 'row_1' : 'row_3' ] )
print()
print('멀티인덱스 [] - \n' , frm.iloc[ [ 0 , 2] ] )
print('슬라이싱   [] - \n' , frm.iloc[ 0 : 3 ] )

인덱스 사용 - loc[]
라벨값 기반 -  [100 101 102 103]
정수값 기반 -  [100 101 102 103]

멀티인덱스 [] - 
        feature_1  feature_2  feature_3  feature_4
row_1        100        101        102        103
row_3        108        109        110        111
슬라이싱   [] - 
        feature_1  feature_2  feature_3  feature_4
row_1        100        101        102        103
row_2        104        105        106        107
row_3        108        109        110        111

멀티인덱스 [] - 
        feature_1  feature_2  feature_3  feature_4
row_1        100        101        102        103
row_3        108        109        110        111
슬라이싱   [] - 
        feature_1  feature_2  feature_3  feature_4
row_1        100        101        102        103
row_2        104        105        106        107
row_3        108        109        110        111


In [34]:
frm.loc[ frm['feature_2'].values > 105 ] 

feature_1  feature_2  feature_3  feature_4
row_3        108        109        110        111

In [40]:
print('행, 열 - ') # frm[열][행] , frm.loc , frm.iloc[행, 열]
print('첫번재 행의 모든 열을 추출 - iloc , loc ') 
print( frm.iloc[ 0 ,  0 : 3 ])
print( frm.loc[ 'row_1' ,  'feature_1' : 'feature_4' ])

행, 열 - 
첫번재 행의 모든 열을 추출 - iloc , loc 
feature_1    100
feature_2    101
feature_3    102
Name: row_1, dtype: int32
feature_1    100
feature_2    101
feature_3    102
feature_4    103
Name: row_1, dtype: int32


In [42]:
print('새로운 행을 추가 - ') 
frm.loc['row_4'] = 200
frm

새로운 행을 추가 - 


feature_1  feature_2  feature_3  feature_4
row_1        100        101        102        103
row_2        104        105        106        107
row_3        108        109        110        111
row_4        200        200        200        200

In [43]:
frm.loc['row_5'] = frm.loc['row_4']
frm

feature_1  feature_2  feature_3  feature_4
row_1        100        101        102        103
row_2        104        105        106        107
row_3        108        109        110        111
row_4        200        200        200        200
row_5        200        200        200        200

In [48]:
scores = {
    'kor' : [90, 85, 100, 88, 78] , 
    'eng' : [67, 56, 100, 78, 89] , 
    'math': [67, 45, 100, 34, 56]
}
frm = pd.DataFrame(scores , 
                   index = ['김채아',  '오세헌' , '★임정섭★' , '전진호', '박영빈'])
frm

kor  eng  math
김채아     90   67    67
오세헌     85   56    45
★임정섭★  100  100   100
전진호     88   78    34
박영빈     78   89    56

In [57]:
print('Q1) 모든 학생의 과목평균 점수를 새로운 열 추가')
# frm.values 
frm['mean'] = np.mean( frm.values  , axis = 1).round(2)
frm

Q1) 모든 학생의 과목평균 점수를 새로운 열 추가


kor  eng  math    mean
김채아     90   67    67   74.67
오세헌     85   56    45   62.00
★임정섭★  100  100   100  100.00
전진호     88   78    34   66.67
박영빈     78   89    56   74.33

In [63]:
print('Q2) 오세헌 학생의 영어점수를 90점으로 수정하고 평균 점수도 다시계산')
frm.loc['오세헌', 'eng'] = 90
frm['mean'] = np.mean( frm.values  , axis = 1).round(2)
frm

Q2) 오세헌 학생의 영어점수를 90점으로 수정하고 평균 점수도 다시계산


kor  eng  math    mean
김채아     90   67    67   74.67
오세헌     85   90    45   70.50
★임정섭★  100  100   100  100.00
전진호     88   78    34   66.67
박영빈     78   89    56   74.33

In [66]:
print('Q3) 전지호 학생의 점수를 데이터프레임으로 추출')
frm.loc[['전진호']]

Q3) 전지호 학생의 점수를 데이터프레임으로 추출


kor  eng  math   mean
전진호   88   78    34  66.67

In [69]:
print('Q4) 김채아 학생의 점수를 시리즈로 추출')
frm.loc['김채아' , : ]

Q4) 김채아 학생의 점수를 시리즈로 추출


kor     90.00
eng     67.00
math    67.00
mean    74.67
Name: 김채아, dtype: float64

In [75]:
print('Q5) 박영빈 학생의 국어,수학점수를 95점으로 수정하고 평균 점수도 다시계산')
frm.loc['박영빈', 'kor']  = 95
frm.loc['박영빈', 'math'] = 95
# frm[['kor', 'eng' , 'math']]
frm['mean'] = np.mean( frm[['kor', 'eng' , 'math']]  , axis = 1).round(2)
frm

Q5) 박영빈 학생의 국어,수학점수를 95점으로 수정하고 평균 점수도 다시계산


kor  eng  math    mean
김채아     90   67    67   74.67
오세헌     85   90    45   73.33
★임정섭★  100  100   100  100.00
전진호     88   78    34   66.67
박영빈     95   89    95   93.00

In [80]:
titanicFrm = sns.load_dataset('titanic')
print('type - ' , type(titanicFrm ))
titanicFrm.head()

type -  <class 'pandas.core.frame.DataFrame'>


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [81]:
titanicFrm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [84]:
print('선실등급의 인원 수를 확인하고 싶다면 - ') 
titanicFrm['pclass'].value_counts().values

선실등급의 인원 수를 확인하고 싶다면 - 


array([491, 216, 184], dtype=int64)

In [85]:
print('프레임의 컬럼명을 확인하고 싶다면 - ') 
titanicFrm.columns

프레임의 컬럼명을 확인하고 싶다면 - 


Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [91]:
print('Q1) age_by_10 컬럼을 추가하고 싶다(기존나이에 10살을 더한 값을) ')
titanicFrm['age_by_10'] = ((titanicFrm['age'] + 10).values).astype('int') 
titanicFrm.head()

Q1) age_by_10 컬럼을 추가하고 싶다(기존나이에 10살을 더한 값을) 


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  
0    man        True  NaN  Southampton    no  False         32  
1  woman       False    C    Cherbourg   yes  False         48  
2  woman       False  NaN  Southampton   yes   True         36  
3  woman       False    C  Southampton   yes  False         45  
4    man        True  NaN  Southampton    no   True         45

In [92]:
print('Q2) parch와 sibsp 더한값에 1을 추가해서 family_no 컬럼추가')
titanicFrm['family_no'] = titanicFrm['parch'] + titanicFrm['sibsp'] + 1   
titanicFrm.head()

Q2) parch와 sibsp 더한값에 1을 추가해서 family_no 컬럼추가


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
0    man        True  NaN  Southampton    no  False         32          2  
1  woman       False    C    Cherbourg   yes  False         48          2  
2  woman       False  NaN  Southampton   yes   True         36          1  
3  woman       False    C  Southampton   yes  False         45          2  
4    man        True  NaN  Southampton    no   True         45          1

In [95]:
print('Q3) 방금 만든 2개의 컬럼을 삭제하고 싶다면 - ') 
print('drop( , axis = 1 )')
titanicFrm.drop(['age_by_10' , 'family_no'] , axis = 1 , inplace = True) 

Q3) 방금 만든 2개의 컬럼을 삭제하고 싶다면 - 
drop( , axis = 1 )


In [96]:
titanicFrm.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [102]:
print('Q4) 요금(fare)에 대한 통계(최대, 최소, 평균, 합계) 확인이 필요하다 - ') 
print('sum - ' , np.sum(titanicFrm['fare'].values))

Q4) 요금(fare)에 대한 통계(최대, 최소, 평균, 합계) 확인이 필요하다 - 
sum -  28693.9493


In [110]:
print('Q5) 선실등급이 3 등급인 데이터만의 subset 만들어라 - ')
pclassFrm = titanicFrm[ titanicFrm['pclass'] == 3 ]
pclassFrm

Q5) 선실등급이 3 등급인 데이터만의 subset 만들어라 - 


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0           0       3    male  22.0      1      0   7.2500        S  Third   
2           1       3  female  26.0      0      0   7.9250        S  Third   
4           0       3    male  35.0      0      0   8.0500        S  Third   
5           0       3    male   NaN      0      0   8.4583        Q  Third   
7           0       3    male   2.0      3      1  21.0750        S  Third   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
882         0       3  female  22.0      0      0  10.5167        S  Third   
884         0       3    male  25.0      0      0   7.0500        S  Third   
885         0       3  female  39.0      0      5  29.1250        Q  Third   
888         0       3  female   NaN      1      2  23.4500        S  Third   
890         0       3    male  32.0      0      0   7.7500        Q  Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
2    woman       False  NaN  Southampton   yes   True  
4      man        True  NaN  Southampton    no   True  
5      man        True  NaN   Queenstown    no   True  
7    child       False  NaN  Southampton    no  False  
..     ...         ...  ...          ...   ...    ...  
882  woman       False  NaN  Southampton    no   True  
884    man        True  NaN  Southampton    no   True  
885  woman       False  NaN   Queenstown    no  False  
888  woman       False  NaN  Southampton    no  False  
890    man        True  NaN   Queenstown    no   True  

[491 rows x 15 columns]

In [113]:
print('Q6) 선실등급이 3 등급인 데이터의 subset 만들고 sex, who 데이터만 추출 - ')
# pclassFrm[['sex', 'who']]
pclassFrm.loc[ : , ['sex', 'who']]

Q6) 선실등급이 3 등급인 데이터의 subset 만들고 sex, who 데이터만 추출 - 


sex    who
0      male    man
2    female  woman
4      male    man
5      male    man
7      male  child
..      ...    ...
882  female  woman
884    male    man
885  female  woman
888  female  woman
890    male    man

[491 rows x 2 columns]

Q01) 다음 조건을 만족하는 임의의 데이터 프레임을 작성해 보자

조건) 열의 갯수와 행의 갯수가 각각 5개 이상이여야 한다.
조건) 열에는 정수, 문자, 실수, 날짜 데이터가 각각 1개이상 포함되어야 한다.



Q02) 제공된 booklist_json.json 파일로부터 데이터를 읽어 들여서 데이터 프레임을 작성해 보자

hint) numpy 파일 입출력
json.loads() : json으로 된 문자열 파일을 읽어들일 때
json.load()  : json 파일을 읽어들일 때