numpy 학습목표
- 배열의 데이터 타입(인공지능에서 사용하게 되는 데이터타입) # 인공지능의 데이터타입들은 대부분 배열로 사용한다.
- 생성, 다루는 방법
- 통계에 관련된 함수를 지원
- 벡터화 연산, 행렬 연산
- 파이썬의 리스트와는 다르다(요소의 타입이 같아야 한다.)
- 원소의 개수를 변경할 수 없다.(resizing X)
- 배열의 차원, 크기, 타입(ndim, shape, dtype)

In [4]:
import numpy  as np
import pandas as pd

- 배열을 생성하는 함수 : array() , arange() , reshape()

In [5]:
lst = [1,2,3,4,5]
print('type - ',type(lst))

ary = np.array(lst)
print('type -  ',type(ary))
print('shape - ',ary.shape) #shape은 크기 (5)
print('ndim -  ',ary.ndim)  #ndim은 차원 (1)
print('dtype - ',ary.dtype)

type -  <class 'list'>
type -   <class 'numpy.ndarray'>
shape -  (5,)
ndim -   1
dtype -  int32


In [6]:
def aryInfo(ary) :
    print('type -',type(ary))
    print('shape -',ary.shape)
    print('ndim -',ary.ndim)
    print('dtype -',ary.dtype)
    print()
    print('data -')
    print(ary)

In [7]:
aryInfo(ary)

type - <class 'numpy.ndarray'>
shape - (5,)
ndim - 1
dtype - int32

data -
[1 2 3 4 5]


In [8]:
lst = [1,2,3,4,5,6,7,8,9]
print(lst * 2) 

ary = np.array(lst)
print(ary ** 2) #벡터와연산

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 1  4  9 16 25 36 49 64 81]


In [9]:
print('산술 연산 - ')
ary01 = np.array([1, 2, 3, 4, 5 ])
ary02 = np.array([10,20,30,40,50])

print(ary01 + ary02) # 배열의 shape이 동일, 연산이 가능


산술 연산 - 
[11 22 33 44 55]


In [10]:
print('비교연산 - ')
print( ary01 == 2 )

booleanMasking = (ary01 == 2)
print(booleanMasking)
print('indexing - ',ary01[0])
print('indexing - ',ary01[1])
print('slicing  - ',ary01[0:3])
print('boolean indxing - ',ary01[booleanMasking]) # True인 값만을 돌려준다.


비교연산 - 
[False  True False False False]
[False  True False False False]
indexing -  1
indexing -  2
slicing  -  [1 2 3]
boolean indxing -  [2]


In [11]:
print('논리연산 - ')

print(ary02 > 10)
print()
print(ary01 == 2)
print(ary02 > 10)
print((ary01 == 2) & (ary02 > 10))
print((ary01 == 2) | (ary02 > 10))

논리연산 - 
[False  True  True  True  True]

[False  True False False False]
[False  True  True  True  True]
[False  True False False False]
[False  True  True  True  True]


- 2차원 배열(행렬, matrix) : list of list # 인공지능 데이터들은 행렬을 많이 사용한다.

In [12]:
# 데이터 분석은 col을 기준으로 분석( col = 1차원 )
print('2 * 3 배열을 생성하고 싶다면 ? ')

lst = [[1,2,3],[4,5,6]] #2행 3열
for ridx, row in enumerate(lst):
    for cidx, col in enumerate(row):
        #print(col)
        #print(ridx)
        #print(cidx)
        print(lst[ridx][cidx], end = '\t')
# print(lst[0][0])

2 * 3 배열을 생성하고 싶다면 ? 
1	2	3	4	5	6	

In [13]:
ary = np.array(lst)
aryInfo(ary)
print()
print(len(ary))
print(len(ary[0]))

type - <class 'numpy.ndarray'>
shape - (2, 3)
ndim - 2
dtype - int32

data -
[[1 2 3]
 [4 5 6]]

2
3


In [14]:
print('2*3*4 배열을 생성하고 싶다면') # 3행 4열짜리 배열이 2개 있는 것이다.
lst = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
       [[13,14,15,16],[17,18,19,20],[21,22,23,24]]
      ]
ary = np.array(lst, dtype = object)
aryInfo(ary)
print()
print(len(ary))
print(len(ary[0]))
print(len(ary[0][0]))
                                           

2*3*4 배열을 생성하고 싶다면
type - <class 'numpy.ndarray'>
shape - (2, 3, 4)
ndim - 3
dtype - object

data -
[[[1 2 3 4]
  [5 6 7 8]
  [9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

2
3
4


- astype() : 요소의 타입을 변경할 때
- 1차원, 2차원 적용이 가능

In [15]:
aryInfo(ary.astype(np.int32))

type - <class 'numpy.ndarray'>
shape - (2, 3, 4)
ndim - 3
dtype - int32

data -
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


- 배열에서 인덱싱, 슬라이싱

In [16]:
print('2차원 배열의 인덱싱 = [행,열]')
print()
ary = np.array([[1,2,3,4] , [5,6,7,8]])
aryInfo(ary)
print()
print('첫번째 행의 첫번째 열의 값을 추출 -',ary[0,0])
print('두번째 행의 첫번째 열의 값을 추출 -',ary[1,0])
print('마지막 행의 마지막 열의 값을 추출 -',ary[-1,-1])
print('첫번째 행의 전체 열의 값을 추출 -',ary[0,:])
print('두번째 행의 전체 열의 값을 추출 -',ary[1])
print('두번째 행의 두번째 열부터 끝까지 값을 추출 -',ary[1,1:])



2차원 배열의 인덱싱 = [행,열]

type - <class 'numpy.ndarray'>
shape - (2, 4)
ndim - 2
dtype - int32

data -
[[1 2 3 4]
 [5 6 7 8]]

첫번째 행의 첫번째 열의 값을 추출 - 1
두번째 행의 첫번째 열의 값을 추출 - 5
마지막 행의 마지막 열의 값을 추출 - 8
첫번째 행의 전체 열의 값을 추출 - [1 2 3 4]
두번째 행의 전체 열의 값을 추출 - [5 6 7 8]
두번째 행의 두번째 열부터 끝까지 값을 추출 - [6 7 8]


In [17]:
print('fancy indexing - 정수배열 인덱싱(첨자), 불리언배열 인덱싱(T|F)')
print()
ary = np.array([0,1,2,3,4,5,6,7,8,9])
aryInfo(ary)
print()
print('2의 배수인것들만 출력한다면 - ')
# print('dir - ',dir(ary)) # __iter 배열도 순환반복이 가능

# for data in ary:
#     if data%2 == 0:
#         print(data)

print('boolean indexing - ',ary[ary%2==0]) # boolean식을 ary의 인덱싱란에 넣으면 for반복과 똑같은 결과가 출력된다.
evenidx = np.array([9,2,4,6,8])
print('정수배열 인덱싱 - ' , ary[evenidx])

fancy indexing - 정수배열 인덱싱(첨자), 불리언배열 인덱싱(T|F)

type - <class 'numpy.ndarray'>
shape - (10,)
ndim - 1
dtype - int32

data -
[0 1 2 3 4 5 6 7 8 9]

2의 배수인것들만 출력한다면 - 
boolean indexing -  [0 2 4 6 8]
정수배열 인덱싱 -  [9 2 4 6 8]


돌발퀴즈
- 3의 배수만 출력
- 4로 나누어 1이 남는 값들만 출력
- 3의 배수이고 4로 나누어 1이 남는 값들만 출력

In [18]:
ary = np.arange(1, 21)
aryInfo(ary)
print(ary[ary%3==0])
print(ary[ary%4==1])
print(ary[(ary%3==0) & (ary%4==1)]) #모호성 오류시 괄호로 묶어줘야함.

type - <class 'numpy.ndarray'>
shape - (20,)
ndim - 1
dtype - int32

data -
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


 - reshape() : 배열의 변형

In [21]:
ary = np.arange(1,13).reshape(-1 , 4) #행과 열중 하나만 지정하면 나머지엔 -1을 넣을 것.
aryInfo(ary)
colTmp = [0,3] # 정수배열 인덱싱
# rowTmp = [0,1,2]
print()
print('정수배열인덱싱을 이용해서 모든 행의 0,3 열 값 출력 - ', ary[:,colTmp]) #ary[0][colTmp],ary[1][colTmp],ary[2][colTmp])
boolTmp = [True,False,False,True] # 불인덱싱
print('불리언배열인덱싱을 이용해서 모든 행의 0,3 열 값 출력 - ',ary[:,boolTmp])
print('5 값 추출 - ', ary[1][0])
print('[2 10] 값 추출 - ', ary[ [0,2] , 1 ])

print('[[2] [10]] 값 추출 - ',ary[ [0,2] , 1:2 ]) #슬라이싱 하면 2차원의 데이터로 가져온다.
print('[[1 3][9 11]] 값 추출',ary[ [0,2] , ::2 ]) # ary[np.ix_([0,2],[0,2])]


type - <class 'numpy.ndarray'>
shape - (3, 4)
ndim - 2
dtype - int32

data -
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

정수배열인덱싱을 이용해서 모든 행의 0,3 열 값 출력 -  [[ 1  4]
 [ 5  8]
 [ 9 12]]
불리언배열인덱싱을 이용해서 모든 행의 0,3 열 값 출력 -  [[ 1  4]
 [ 5  8]
 [ 9 12]]
5 값 추출 -  5
[2 10] 값 추출 -  [ 2 10]
[[2] [10]] 값 추출 -  [[ 2]
 [10]]
[[1 3][9 11]] 값 추출 [[ 1  3]
 [ 9 11]]
