In [1]:
import numpy  as np 
import pandas as pd

def aryInfo(ary) : 
    print('type - ' , type(ary)) 
    print('shape - ' , ary.shape)
    print('ndim  - ' , ary.ndim)
    print('dtype - ' , ary.dtype)
    print()
    print('data  -')
    print(ary) 

- 전치행렬(transpose matirx)
- T

In [5]:
ary = np.arange(1,7).reshape(2,3)
aryInfo(ary)
print()
transposeAry = ary.T
aryInfo(transposeAry)


type -  <class 'numpy.ndarray'>
shape -  (2, 3)
ndim  -  2
dtype -  int32

data  -
[[1 2 3]
 [4 5 6]]

type -  <class 'numpy.ndarray'>
shape -  (3, 2)
ndim  -  2
dtype -  int32

data  -
[[1 4]
 [2 5]
 [3 6]]


In [11]:
print('1차원 배열에 대한 전치행렬이 필요할까요? ') 
print('정답 : 필요하다 ')
print('이유는 : 함수의 인자로 배열 넘길때 타입이 맞아야 하므로') 
ary = np.arange(1 , 7)
aryInfo(ary)

transposeAry = ary.reshape(1,6).T
aryInfo(transposeAry)

1차원 배열에 대한 전치행렬이 필요할까요? 
정답 : 필요하다 
이유는 : 함수의 인자로 배열 넘길때 타입이 맞아야 하므로
type -  <class 'numpy.ndarray'>
shape -  (6,)
ndim  -  1
dtype -  int32

data  -
[1 2 3 4 5 6]
type -  <class 'numpy.ndarray'>
shape -  (6, 1)
ndim  -  2
dtype -  int32

data  -
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


- flatten : 다차원 배열을 1차원으로 바꿀때

In [13]:
aryInfo(transposeAry.flatten() )

type -  <class 'numpy.ndarray'>
shape -  (6,)
ndim  -  1
dtype -  int32

data  -
[1 2 3 4 5 6]


- 주의사항) 차원에 대한 주의가 필요함

In [17]:
ary = np.arange(10)
aryInfo(ary)

print()

print( ary.reshape(1, 10))
print( ary.reshape(10, 1))

print()
print('차원의 변경이 아니라 차원증가 - np.newaxis')
print()
print( ary[ np.newaxis , : ] )
print( ary[ : ,  np.newaxis ] )


type -  <class 'numpy.ndarray'>
shape -  (10,)
ndim  -  1
dtype -  int32

data  -
[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

차원의 변경이 아니라 차원증가 - np.newaxis

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


- 배열연결

In [28]:
print('hstack() - 행의갯수가 동일한 두개의 배열을 연결 - ') 
ary01 = np.ones((3,4))
ary02 = np.zeros((3,4))

hstack() - 행의갯수가 동일한 두개의 배열을 연결 - 


In [29]:
aryInfo(ary01)
print()
aryInfo(ary02)
print()
print('hstack - ')
print( np.hstack([ary01, ary02]))

type -  <class 'numpy.ndarray'>
shape -  (3, 4)
ndim  -  2
dtype -  float64

data  -
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

type -  <class 'numpy.ndarray'>
shape -  (3, 4)
ndim  -  2
dtype -  float64

data  -
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

hstack - 
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]


In [30]:
print('vstack() - 열의갯수가 동일한 두개의 배열을 연결 - ') 
ary01 = np.ones((3,4))
ary02 = np.zeros((3,4))

vstack() - 열의갯수가 동일한 두개의 배열을 연결 - 


In [31]:
print('vstack - ')
print( np.vstack([ary01, ary02]))

vstack - 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
print(ary01)
print()
print(ary02)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
print('stack - 사용자가 지정한 축(x,y)')
print('축 axis = 0 , axis = 1')
print('shape axis=0 - 2*3*4 , axis=1 3*2*4 ')
ary01 = np.ones((3,4))
ary02 = np.zeros((3,4))

aryInfo( np.stack([ary01, ary02] , axis =1))

stack - 사용자가 지정한 축(x,y)
축 axis = 0 , axis = 1
shape axis=0 - 2*3*4 , axis=1 3*2*4 
type -  <class 'numpy.ndarray'>
shape -  (3, 2, 4)
ndim  -  3
dtype -  float64

data  -
[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]


In [44]:
print('tile() - 동일한 배열을 반복하여 연결') 
ary = np.arange(1,7).reshape(-1,3)
np.tile(ary , (3,3))

tile() - 동일한 배열을 반복하여 연결


array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

- 돌발퀴즈

In [ ]:
# 아래 결과가 나올 수 있도록 np.함수()를 이용하여 작성해 보세요~~~
# 
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])

In [53]:
ary01 = np.zeros((3,3))
ary02 = np.ones((3,2))
ary03 = np.hstack([ary01 , ary02])
# print(ary03)
ary04 = np.arange(10, 160 , 10).reshape(3,5) 
ary05 = np.vstack([ary03 , ary04])
# print(ary05)
answerAry = np.tile(ary05 , (2,1))
print(answerAry)

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


데이터 삭제
- delete()
- 기준 axis = 0(행) , axis = 1(열) 
- 기준을 정의하지 않는다면 1차원변경 삭제
- 리턴이 있다(원본배열에 적용하는 것이 아니라 변경된 새로운 리턴) 

In [79]:
ary = np.random.randint(0, 10 , (3,4))
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (3, 4)
ndim  -  2
dtype -  int32

data  -
[[3 9 3 0]
 [6 1 1 8]
 [5 8 1 6]]


In [82]:
newAry = np.delete(ary , 1 , axis = 0)
newAry

array([[3, 9, 3, 0],
       [5, 8, 1, 6]])

In [84]:
np.delete(ary , 1)

array([3, 3, 0, 6, 1, 1, 8, 5, 8, 1, 6])

통계함수(차원축소 함수 == dimension reduction)
- 기술적통계(min, max, sum, mean, median, std, var, etc...) 
- all, any
- 중요) argmin , argmax : 인덱스를 리턴한다

In [98]:
ary = np.array([1,2,3,4,5,6,7,8,9,10]) 
print('data   - ' , ary.shape , ary.ndim , ary.dtype)
print('sum    - ' , np.sum(ary) , ary.sum())
print('mean   - ' , np.mean(ary))
print('median - ' , np.median(ary))
print('max    - ' , np.max(ary))
print('min    - ' , np.min(ary))
print('var    - ' , np.var(ary))
print('std    - ' , np.std(ary))
print('quartile - ' , np.percentile(ary, 0))
print('quartile - ' , np.percentile(ary, 25))
print('quartile - ' , np.percentile(ary, 50))
print('quartile - ' , np.percentile(ary, 75))
print('quartile - ' , np.percentile(ary, 100))


data   -  (10,) 1 int32
sum    -  55 55
mean   -  5.5
median -  5.5
max    -  10
min    -  1
var    -  8.25
std    -  2.8722813232690143
quartile -  1.0
quartile -  3.25
quartile -  5.5
quartile -  7.75
quartile -  10.0


In [104]:
print('argmin - ' , ary[ np.argmin(ary) ] )
print('argmax - ' , ary[ np.argmax(ary) ] )
print()
print('any - ' , np.any([True , False , True]))
print('all - ' , np.all([True , False , True]))

argmin -  1
argmax -  10

any -  True
all -  False


In [105]:
ary = np.arange(1, 21).reshape(4, -1)
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (4, 5)
ndim  -  2
dtype -  int32

data  -
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [112]:
print('2차원 배열에서 차원축소함수를 적용하기 위해서는 axis 설정이 중요 - ') 
print('0 : 열 , 1 : 행')
print('sum - ' , np.sum(ary) , type(np.sum(ary)))
print('sum - ' , np.sum(ary , axis = 0) , type(np.sum(ary , axis = 0)))
print('sum - ' , np.sum(ary , axis = 1) , type(np.sum(ary , axis = 0)))


2차원 배열에서 차원축소함수를 적용하기 위해서는 axis 설정이 중요 - 
0 : 열 , 1 : 행
sum -  210 <class 'numpy.int32'>
sum -  [34 38 42 46 50] <class 'numpy.ndarray'>
sum -  [15 40 65 90] <class 'numpy.ndarray'>


돌발퀴즈

In [113]:
ary = np.random.randint(0, 1000000 , (5,6))
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (5, 6)
ndim  -  2
dtype -  int32

data  -
[[490192 818226 403137 924966   6165 220678]
 [928877 214309 532538 228294 408598 220458]
 [ 71960 472782 508188 721393  16703 290552]
 [255931 765501 857310 289099 721990 294127]
 [677181 791233 156309 594153 846434 529179]]


In [143]:
print('전체의 최대값 - ' , np.max(ary))
print('행 합 - ' , np.sum(ary , axis = 1) , np.sum(ary , axis = 1).shape)
sumAry = np.sum(ary , axis = 1).reshape(5, -1)
print('행 합을 열로 추가 - ')  
print(np.hstack([ary , sumAry]))

print( np.array([ ary[idx].sum() for idx in range(ary.shape[0])]) )

print()
print()
print('각 행의 최대값 - ' , np.max(ary , axis = 1))
maxAry = np.max(ary , axis = 1).reshape(5, -1)
print('각 행의 최대값 열로 추가 - ' , np.hstack( [ary , maxAry]))
print('각 열의 평균 - ' , np.mean(ary, axis = 0))
meanAry = np.mean(ary, axis = 0).reshape(1, -1)
print('meanAry shape - ' , meanAry.shape)
print()
print('각 열의 평균을 행으로 추가 - ' , np.vstack([ary , meanAry]))
print()
print('각 열의 최소값 - ' , np.min(ary , axis = 0))

전체의 최대값 -  928877
행 합 -  [2863364 2533074 2081578 3183958 3594489] (5,)
행 합을 열로 추가 - 
[[ 490192  818226  403137  924966    6165  220678 2863364]
 [ 928877  214309  532538  228294  408598  220458 2533074]
 [  71960  472782  508188  721393   16703  290552 2081578]
 [ 255931  765501  857310  289099  721990  294127 3183958]
 [ 677181  791233  156309  594153  846434  529179 3594489]]
[2863364 2863364 2863364 2863364 2863364]


각 행의 최대값 -  [924966 928877 721393 857310 846434]
각 행의 최대값 열로 추가 -  [[490192 818226 403137 924966   6165 220678 924966]
 [928877 214309 532538 228294 408598 220458 928877]
 [ 71960 472782 508188 721393  16703 290552 721393]
 [255931 765501 857310 289099 721990 294127 857310]
 [677181 791233 156309 594153 846434 529179 846434]]
각 열의 평균 -  [484828.2 612410.2 491496.4 551581.  399978.  310998.8]
meanAry shape -  (1, 6)

각 열의 평균을 행으로 추가 -  [[490192.  818226.  403137.  924966.    6165.  220678. ]
 [928877.  214309.  532538.  228294.  408598.  220458. ]
 [ 71960.  472782.  5

sorting
- np.sort()  : 원본에 대한 변경 X(inplace = False) 
- ary.sort() : 원본에 대한 변경 O(inplace = True)

In [152]:
ary = np.arange(10)
print(ary)
print()
np.random.shuffle(ary)
print(ary)
print('np.sort - ') 
newAry = np.sort(ary)
print(newAry)
print('ary - ' , ary)
print('desc - ') 
newAry = np.sort(ary)[::-1]
print(newAry)

[0 1 2 3 4 5 6 7 8 9]

[3 0 1 5 4 7 8 6 9 2]
np.sort - 
[0 1 2 3 4 5 6 7 8 9]
ary -  [3 0 1 5 4 7 8 6 9 2]
desc - 
[9 8 7 6 5 4 3 2 1 0]


In [161]:
print('행렬에 대한 정렬 - ') 
ary = np.random.randint(1, 17, (4,4))
print(ary)

행렬에 대한 정렬 - 
[[ 4  3 11 11]
 [ 1  5 13  3]
 [ 7 12 11  2]
 [ 3 14 10  6]]


In [164]:
print('열 정렬 - ') 
print(np.sort(ary , axis = 0))
print()
print(ary)
print()
print('행 정렬 - ')
print(np.sort(ary , axis = 1))
print()

열 정렬 - 
[[ 1  3 10  2]
 [ 3  5 11  3]
 [ 4 12 11  6]
 [ 7 14 13 11]]

[[ 4  3 11 11]
 [ 1  5 13  3]
 [ 7 12 11  2]
 [ 3 14 10  6]]

행 정렬 - 
[[ 3  4 11 11]
 [ 1  3  5 13]
 [ 2  7 11 12]
 [ 3  6 10 14]]



- 만약, 정렬된 인덱스를 필요로 한다면?
- np.argsort()

In [165]:
ary = np.array([4,3,5,7]) 
print(ary)

[4 3 5 7]


In [169]:
sortIdx = np.argsort(ary)
print(sortIdx)
print()
print(ary[sortIdx])
print(ary[sortIdx][::-1])

[1 0 2 3]

[3 4 5 7]
[7 5 4 3]


In [170]:
ary =  np.random.randint(1, 17 , (4,4))
print(ary)

[[ 1  3 13 11]
 [ 5 11 14 11]
 [ 1  2 16  9]
 [10  2  5  8]]


In [173]:
np.argsort(ary , axis = 0)

array([[0, 2, 3, 3],
       [2, 3, 0, 2],
       [1, 0, 1, 0],
       [3, 1, 2, 1]], dtype=int64)

- 배열에 병합이 아닌 열, 행 추가하는 방법
- np.concatenate() 
- 축의 방향을 설정하여 추가 axis = 

In [175]:
ary = np.array([[1,2,3] , [4,5,6]]) 
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (2, 3)
ndim  -  2
dtype -  int32

data  -
[[1 2 3]
 [4 5 6]]


In [184]:
rowAry = np.array([7,8,9]) 
# np.vstack([ary, rowAry])
print( np.concatenate( (ary, rowAry[ np.newaxis , : ]) , axis = 0) )
print()
print( np.concatenate( (ary, rowAry.reshape(1,3)) , axis = 0) )
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [186]:
# print(ary)

colAry = np.array([10,11])

print( np.concatenate( (ary, colAry[ : , np.newaxis  ]) , axis = 1) )
print()
print( np.concatenate( (ary, colAry.reshape(2,1)) , axis = 1) )

[[ 1  2  3 10]
 [ 4  5  6 11]]

[[ 1  2  3 10]
 [ 4  5  6 11]]
