In [59]:
import numpy  as np
import pandas as pd

def aryInfo(ary) :
    print('type -',type(ary))
    print('shape -',ary.shape)
    print('ndim -',ary.ndim)
    print('dtype -',ary.dtype)
    print()
    print('data -')
    print(ary)

- 전치행렬(transpose matrix)
- T

In [60]:
ary = np.arange(1,7).reshape(2,3)
aryInfo(ary)
print()
transposeAry = ary.T
aryInfo(transposeAry) # 2행3열이 3행2열로 바뀐다.

type - <class 'numpy.ndarray'>
shape - (2, 3)
ndim - 2
dtype - int32

data -
[[1 2 3]
 [4 5 6]]

type - <class 'numpy.ndarray'>
shape - (3, 2)
ndim - 2
dtype - int32

data -
[[1 4]
 [2 5]
 [3 6]]


In [61]:
print('1차원 배열에 대한 전치행렬이 필요할까요?')
print('정답 : 필요하다')
print('이유는 : 함수의 인자로 배열 넘길 떄 타입이 맞아야 하므로')
ary = np.arange(1,7)
aryInfo(ary)
transposeAry = ary.reshape(1,6).T
aryInfo(transposeAry) #1차원을 2차원으로 만들어서 Transpose 시키기 가능하다.

1차원 배열에 대한 전치행렬이 필요할까요?
정답 : 필요하다
이유는 : 함수의 인자로 배열 넘길 떄 타입이 맞아야 하므로
type - <class 'numpy.ndarray'>
shape - (6,)
ndim - 1
dtype - int32

data -
[1 2 3 4 5 6]
type - <class 'numpy.ndarray'>
shape - (6, 1)
ndim - 2
dtype - int32

data -
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


- flatten : 다차원 배열을 1차원으로 바꿀때 

In [62]:
aryInfo(transposeAry.flatten()) #기존 2차원 배열이 1차원으로 변경된다.

type - <class 'numpy.ndarray'>
shape - (6,)
ndim - 1
dtype - int32

data -
[1 2 3 4 5 6]


- 주의사항) 차원에 대한 주의가 필요하다. 

In [63]:
ary = np.arange(10)
aryInfo(ary)

print()

print(ary.reshape(1,10)) # 1행 10열의 2차원
print(ary.reshape(10,1)) # 10행 1열의 2차원

print()
print('차원의 변경이 아니라 차원증가 - np.newaxis')
print()
print( ary[ np.newaxis , : ] ) # 차원증가를 통해 2차원으로 가능
print( ary[ : , np.newaxis ] ) # 열방향의 2차원 증가 #배열의 축의 방향을 통해 2차원으로 증가시킬 수 있다.

type - <class 'numpy.ndarray'>
shape - (10,)
ndim - 1
dtype - int32

data -
[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

차원의 변경이 아니라 차원증가 - np.newaxis

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


- 배열연결 

In [64]:
print('hstack() - 행의 개수가 동일한 두개의 배열을 연결 - ')
ary01 = np.ones((3,4)) # 튜플 형식으로 행,열을 지정
ary02 = np.zeros((3,5))

hstack() - 행의 개수가 동일한 두개의 배열을 연결 - 


In [65]:
aryInfo(ary01)
aryInfo(ary02)
print(np.hstack([ary01,ary02])) #리스트로 묶어주어야 한다., 행의 개수는 같아야 한다.



type - <class 'numpy.ndarray'>
shape - (3, 4)
ndim - 2
dtype - float64

data -
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
type - <class 'numpy.ndarray'>
shape - (3, 5)
ndim - 2
dtype - float64

data -
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0.]]


In [66]:
print('vstack() - 열의 개수가 동일한 두개의 배열을 연결 - ')
ary01 = np.ones((3,4)) # 튜플 형식으로 행,열을 지정
ary02 = np.zeros((3,4))

vstack() - 열의 개수가 동일한 두개의 배열을 연결 - 


In [67]:
aryInfo(ary01)
aryInfo(ary02)
print(np.vstack([ary01,ary02]))

type - <class 'numpy.ndarray'>
shape - (3, 4)
ndim - 2
dtype - float64

data -
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
type - <class 'numpy.ndarray'>
shape - (3, 4)
ndim - 2
dtype - float64

data -
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [68]:
print(ary01)
print()
print(ary02)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [69]:
print('stack - 사용자가 지정한 축(x,y)')
print('축 axis = 0, axis = 1')
print('shpae axis=0, 2*3*4/3행4열2개, axis=1 3*2*4/2행4열3개, ')
ary01 = np.ones((3,4))
ary02 = np.zeros((3,4))

aryInfo(np.stack([ary01, ary02] , axis = 0))

stack - 사용자가 지정한 축(x,y)
축 axis = 0, axis = 1
shpae axis=0, 2*3*4/3행4열2개, axis=1 3*2*4/2행4열3개, 
type - <class 'numpy.ndarray'>
shape - (2, 3, 4)
ndim - 3
dtype - float64

data -
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [70]:
print('tile() - 동일한 배열을 반복하여 연결')
ary = np.arange(1,7).reshape(-1,3)
np.tile(ary,(3,3)) #행과 열을 반복할 수 있음.

tile() - 동일한 배열을 반복하여 연결


array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [71]:
# 위 결과가 나올 수 있도록 함수를 이용하여 작성해 보세요~~~
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])

In [72]:
ary01 = np.zeros((3,3))
ary02 = np.ones((3,2))
# print(ary01)
# print(ary02)
ary03 = np.hstack([ary01,ary02])
ary04 = np.arange(10,160,10).reshape(3,5)
ary05 = np.vstack([ary03,ary04])
# print(ary04)
# print(ary05)
ary06 = np.tile(ary05,(2,1))
print(ary06)

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


데이터 삭제
- delete()
- 기준 axis = 0(행), axis = 1(열)
- 기준을 정의하지 않는다면 1차원변경 삭제
- 리턴이 있다(원본배열에 적용하는 것이 아니라 변경된 새로운 리턴)

In [73]:
ary = np.random.randint(0, 10, (3,4)) #random을 이용해 배열을 만들 수 있다.
aryInfo(ary)

type - <class 'numpy.ndarray'>
shape - (3, 4)
ndim - 2
dtype - int32

data -
[[8 9 2 5]
 [9 5 2 2]
 [2 0 1 8]]


In [74]:
newAry = np.delete(ary, 1 , axis = 0)
newAry

array([[8, 9, 2, 5],
       [2, 0, 1, 8]])

In [75]:
ary

array([[8, 9, 2, 5],
       [9, 5, 2, 2],
       [2, 0, 1, 8]])

통계함수(차원축소 함수 == dimension reduction)
- 기술적통계(min, max, sum, mean, median, std, var, etc....)
- all,any
- 중요) argmin, argmax : 인덱스를 리턴한다.

In [76]:
ary = np.array([1,2,3,4,5,6,7,8,9,10]) #numpy의 함수값들로 이해할 것.
print('data   - ',ary.shape, ary.ndim, ary.dtype)
print('sum    - ',np.sum(ary))
print('mean   - ',np.mean(ary))
print('median - ',np.median(ary))
print('max    - ',np.max(ary))
print('min    - ',np.min(ary))
print('var    - ',np.var(ary))
print('std    - ',np.std(ary))
print('quartile - ', np.percentile(ary,0))
print('quartile - ', np.percentile(ary,100))
print('quartile - ', np.percentile(ary,25)) # 1사분위
print('quartile - ', np.percentile(ary,50)) # 2사분위
print('quartile - ', np.percentile(ary,75)) # 3사분위


data   -  (10,) 1 int32
sum    -  55
mean   -  5.5
median -  5.5
max    -  10
min    -  1
var    -  8.25
std    -  2.8722813232690143
quartile -  1.0
quartile -  10.0
quartile -  3.25
quartile -  5.5
quartile -  7.75


In [77]:
print('argmin - ',ary[np.argmin(ary)]) # idx
print('argmax - ',ary[np.argmax(ary)])
print()
print('any - ',np.any([True,False,True])) # 하나라도 True가 있으면 True (or)
print('all - ',np.all([True,False,True])) # and


argmin -  1
argmax -  10

any -  True
all -  False


In [78]:
ary = np.arange(1,21).reshape(4,5)
print(ary)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [80]:
print('2차원 배열에서 차원축소함수를 적용하기 위해서는 axis 설정이 중요~')
print('sum - ',sum(ary), type(np.sum(ary)))

2차원 배열에서 차원축소함수를 적용하기 위해서는 axis 설정이 중요~
sum -  [34 38 42 46 50] <class 'numpy.int32'>


In [100]:
print('sum - ',sum(ary), type(np.sum(ary)))

sum -  [3133096 2667767 2079508 2172187 2909593 4086382] <class 'numpy.int32'>


돌발퀴즈 

In [86]:
ary = np.random.randint(0, 1000000, (5,6))
aryInfo(ary)

type - <class 'numpy.ndarray'>
shape - (5, 6)
ndim - 2
dtype - int32

data -
[[119399 356271 645555 837647 562740 704277]
 [701967 914337 564253 228816  26946 841344]
 [995145 291891  62243 511057 774890 988160]
 [895828 130848 713737 479700 798658 874441]
 [420757 974420  93720 114967 746359 678160]]


In [133]:
print('전체 최대값 - ',np.max(ary))
print('행 합',np.sum(ary, axis = 1))
print('행의 합을 열로 추가',np.hstack([np.sum(ary, axis = 1).reshape(-1,1), ary]))
print('list comprehension -',[ary[idx].sum() for idx in range(ary.shape[0])])
print('각 행의 최대값',np.max(ary, axis = 1))
print('각 행의 최대값을 열로 추가',np.hstack([np.max(ary, axis = 1).reshape(5,1), ary]))
print('각 열의 평균 - ',np.mean(ary, axis = 0))
print('각 열의 평균을 행으로 추가',np.vstack([np.mean(ary, axis = 0).reshape(1,-1), ary]))
print()
print('각 열의 최소값 -',np.min(ary, axis = 0))

전체 최대값 -  995145
행 합 [3225889 3277663 3623386 3893212 3028383]
행의 합을 열로 추가 [[3225889  119399  356271  645555  837647  562740  704277]
 [3277663  701967  914337  564253  228816   26946  841344]
 [3623386  995145  291891   62243  511057  774890  988160]
 [3893212  895828  130848  713737  479700  798658  874441]
 [3028383  420757  974420   93720  114967  746359  678160]]
list comprehension - [3225889, 3277663, 3623386, 3893212, 3028383]
각 행의 최대값 [837647 914337 995145 895828 974420]
각 행의 최대값을 열로 추가 [[837647 119399 356271 645555 837647 562740 704277]
 [914337 701967 914337 564253 228816  26946 841344]
 [995145 995145 291891  62243 511057 774890 988160]
 [895828 895828 130848 713737 479700 798658 874441]
 [974420 420757 974420  93720 114967 746359 678160]]
각 열의 평균 -  [626619.2 533553.4 415901.6 434437.4 581918.6 817276.4]
각 열의 평균을 행으로 추가 [[626619.2 533553.4 415901.6 434437.4 581918.6 817276.4]
 [119399.  356271.  645555.  837647.  562740.  704277. ]
 [701967.  914337.  564253.  228816.   269

sorting
- np.sort()  : 원본에 대한 변경 x(inplace = False)
- ary.sort() : 원본에 대한 변경 o(inplace = True )

In [168]:
ary = np.arange(10)
print(ary)
print()
np.random.shuffle(ary) #배열이 셔플된다.
print(ary)
print('np.sort - ')
newAry = np.sort(ary) #원본에 반영이 되지 않았다.
print(newAry)
print('ary - ', ary)
print('desc - ')
newAry = np.sort(ary)[::-1]
print(newAry)

[0 1 2 3 4 5 6 7 8 9]

[1 2 4 5 9 0 8 3 6 7]
np.sort - 
[0 1 2 3 4 5 6 7 8 9]
ary -  [1 2 4 5 9 0 8 3 6 7]
desc - 
[9 8 7 6 5 4 3 2 1 0]


In [175]:
print('행렬에 대한 정렬 - ') # 행렬에 대한 정렬이 가능하다.
ary = np.random.randint(1, 17, (4,4))
print(ary)
print()
print('열 정렬 - ')
print(np.sort(ary, axis = 0))
print()
print(ary)
print('행 정렬 -')
print(np.sort(ary, axis = 1))

행렬에 대한 정렬 - 
[[11  1 16 13]
 [ 1  3 14  9]
 [10  8  6 14]
 [ 7 13 11 12]]

열 정렬 - 
[[ 1  1  6  9]
 [ 7  3 11 12]
 [10  8 14 13]
 [11 13 16 14]]

[[11  1 16 13]
 [ 1  3 14  9]
 [10  8  6 14]
 [ 7 13 11 12]]
행 정렬 -
[[ 1 11 13 16]
 [ 1  3  9 14]
 [ 6  8 10 14]
 [ 7 11 12 13]]


- 만약, 정렬된 인덱스를 필요로 한다면?
- np.argsort()

In [179]:
ary = np.array([4,3,5,7])
print(ary)

[4 3 5 7]


In [184]:
sortidx = np.argsort(ary)
print(sortidx) #arg가 붙으면 value 대신 index를 return하게 된다.
print(ary[sortidx])
print(ary[sortidx][::-1])

[1 0 2 3]
[3 4 5 7]
[7 5 4 3]


In [189]:
ary = np.random.randint(1, 17, (4,4))
print(ary)

[[10 12 14  1]
 [14 11  3 12]
 [ 7 13  8  4]
 [ 8 13  6  2]]


In [193]:
np.argsort(ary, axis = 0)

array([[2, 1, 1, 0],
       [3, 0, 3, 3],
       [0, 2, 2, 2],
       [1, 3, 0, 1]], dtype=int64)

- 배열에 병합이 아닌 열, 행 추가하는 방법
- np.concatenate() #추가
- 축의 방향을 설정하여 추가 (axis)

In [195]:
ary = np.array([[1,2,3] , [4,5,6]])
aryInfo(ary)

type - <class 'numpy.ndarray'>
shape - (2, 3)
ndim - 2
dtype - int32

data -
[[1 2 3]
 [4 5 6]]


In [209]:
rowAry = np.array([7,8,9])
np.vstack([ary, rowAry])
print(np.concatenate( (ary, rowAry[ np.newaxis , : ]) , axis = 0))
print()
print(np.concatenate( (ary, rowAry.reshape(1,3)) , axis = 0))
colAry = np.array([10,11])
print(np.concatenate( (ary, colAry[ : , np.newaxis ]) , axis = 1))
print(np.concatenate( (ary, colAry.reshape(2,1)) , axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10]
 [ 4  5  6 11]]
[[ 1  2  3 10]
 [ 4  5  6 11]]
